version: '3.1'

services:
  kitchen:
    image: kitch-image:7.0
    container_name: kitch-pod
    build:
      context: .
      dockerfile: Containerfile
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/mykitchen:z
      ports:
        - 8600:8000
