# Generated by Django 4.2.6 on 2023-10-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=100)),
                ('items', models.CharField(default=[], max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prep_time', models.IntegerField(default=25)),
                ('calories', models.IntegerField(default=1000)),
            ],
        ),
    ]
