# Generated by Django 4.2.6 on 2023-11-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_booking_email_booking_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='items',
        ),
        migrations.AddField(
            model_name='menu',
            name='item_description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
