# Generated by Django 4.2.7 on 2023-11-09 19:50

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_booking_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
