# Generated by Django 4.2.7 on 2023-12-19 20:55

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_alter_booking_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
