# Generated by Django 4.2.7 on 2023-12-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_alter_booking_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='country',
        ),
    ]
