# Generated by Django 4.2.7 on 2023-12-22 16:34

from django.db import migrations
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_remove_booking_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='country',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
