# Generated by Django 4.2.7 on 2023-12-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_alter_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
    ]
