# Generated by Django 4.2.7 on 2026-05-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0019_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
