# Generated by Django 4.2.7 on 2026-05-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_menu_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15),
        ),
    ]
